/** Shared redirects — used in VitePress config (build) and dev middleware. */
export const docRedirects: Record<string, string> = {
  '/index.html': '/',
  '/quickstart.html': '/quickstart',
  '/authentication.html': '/authentication',
  '/principles.html': '/principles',
  '/faq.html': '/faq',
  '/changelog.html': '/changelog',
  '/models.html': '/models/',
  '/models/index.html': '/models/',
  '/vi/index.html': '/vi/',
  '/vi/quickstart.html': '/vi/quickstart',
  '/vi/authentication.html': '/vi/authentication',
  '/vi/principles.html': '/vi/principles',
  '/vi/faq.html': '/vi/faq',
  '/vi/changelog.html': '/vi/changelog',
  '/vi/models.html': '/vi/models/',
  '/vi/models/index.html': '/vi/models/',
  '/reference/playground': '/app/playground/',
  '/reference/playground.html': '/app/playground/',
  '/vi/reference/playground': '/vi/app/playground/',
  '/vi/reference/playground.html': '/vi/app/playground/',
  '/portal': '/app/playground/',
  '/portal/': '/app/playground/',
  '/portal/index.html': '/app/playground/',
  '/portal/playground': '/app/playground/',
  '/portal/playground.html': '/app/playground/',
  '/vi/portal': '/vi/app/playground/',
  '/vi/portal/': '/vi/app/playground/',
  '/vi/portal/index.html': '/vi/app/playground/',
  '/vi/portal/playground': '/vi/app/playground/',
  '/vi/portal/playground.html': '/vi/app/playground/',
};
